name: nextstrain_data_extraction
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - pip:
    - -e git+https://github.com/nextstrain/augur.git@22.4.0#egg=nextstrain-augur
    - biopython==1.81
