name: Pipeline stub test
on: [push, pull_request]

jobs:
  stub_test:
    name: Stub test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        profile: [conda, mamba]
        align_method: [mafft, minimap2]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup for conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: nexus_to_newick
          mamba-version: "*"
          channels: conda-forge,bioconda
          channel-priority: true
          auto-activate-base: true
      - name: Setup nextflow
        uses: nf-core/setup-nextflow@v1.2.0
        with:
          version: 23.04
      - name: Run pipeline ${{ matrix.align_method }} with profile ${{ matrix.profile }}
        run: |
          nextflow -C nextflow.config run main.nf -stub-run -profile ${{ matrix.profile }} --align_method ${{ matrix.align_method }}
