name: Pipeline stub test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  stub_test:
    name: Stub test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        profile: [mamba, docker]
        align_method: [mafft, minimap2]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup for conda
        if : ${{ matrix.profile == 'mamba'}}
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda
          channel-priority: true
          auto-activate-base: true
      - name: Setup nextflow
        uses: nf-core/setup-nextflow@v1.2.0
        with:
          version: 23.04
      - name: Setup docker
        if : ${{ matrix.profile == 'docker' }}
        run: make setup-docker
      - name: Clean conda cache
        if : ${{ matrix.profile == 'mamba' }}
        run: mamba clean --all --yes
      - name: Cache mamba envs
        if : ${{ matrix.profile == 'mamba' }}
        id: cache-mamba-envs
        uses: actions/cache@v3
        with:
          path: ${{ PWD }}/work/conda/
          key: ${{ matrix.profile }}
      - name: Run pipeline ${{ matrix.align_method }} with profile ${{ matrix.profile }}
        run: |
          nextflow -C nextflow.config run main.nf -stub-run -profile ${{ matrix.profile }} --align_method ${{ matrix.align_method }}
