name: Pipeline stub test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  stub_test:
    name: Stub test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        profile: [conda, mamba, docker]
        align_method: [mafft, minimap2]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup for conda
        if : ${{ matrix.profile == 'conda' || matrix.profile == 'mamba'}}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: nexus_to_newick
          mamba-version: "*"
          channels: conda-forge,bioconda
          channel-priority: true
          auto-activate-base: true
      - name: Setup nextflow
        uses: nf-core/setup-nextflow@v1.2.0
        with:
          version: 23.04
      - name: Setup docker
        if : ${{ matrix.profile == 'docker' }}
        run: |
          # get the current directorys parent directory
          DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && cd .. && pwd )"

          # get the list of all the docker files even in the subdirectories
          DOCKER_FILES=$(find $DIR -name "Dockerfile")

          # iterate through all the docker files
          for DOCKER_FILE in $DOCKER_FILES
          do
              # get the directory of the docker file
              DOCKER_FILE_DIR=$(dirname $DOCKER_FILE)
              # get the name of the docker image
              DOCKER_IMAGE_NAME=$(basename $DOCKER_FILE_DIR)
              echo "Building docker image: $DOCKER_IMAGE_NAME"
              # build the docker image
              docker buildx build -t $DOCKER_IMAGE_NAME -f $DOCKER_FILE \
                --cache: "enabled" \
                --cache-to type=gha[mode=min] \
                --cache-from type=gha[mode=min] $DOCKER_FILE_DIR
          done

        
      - name: Run pipeline ${{ matrix.align_method }} with profile ${{ matrix.profile }}
        run: |
          nextflow -C nextflow.config run main.nf -stub-run -profile ${{ matrix.profile }} --align_method ${{ matrix.align_method }}
