name: Pipeline stub test
on: [push, pull_request]

jobs:
  stub_test:
    name: Stub test
    runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup for conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          auto-activate-base: true
      - name: Setup nextflow
        uses: nf-core/setup-nextflow@v1.2.0
        with:
          version: 
      - name: Run pipeline
        run: |
          nextflow -C nextflow.config run main.nf -stub-run -profile conda --align_method mafft
